# Generated by Django 6.0 on 2026-01-22 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="electoralarea",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="electoralarea",
            name="district",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elections.district",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electoralarea",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="elections.province"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="electoral_area",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elections.electoralarea",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vote",
            name="voter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="electoralarea",
            unique_together={("name", "district")},
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("voter", "vote_type")},
        ),
    ]
