# Generated by Django 6.0 on 2026-01-22 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_alter_electoralarea_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electoralarea",
            name="district",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elections.district",
            ),
        ),
    ]
