# Generated by Django 6.0 on 2026-01-22 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_alter_electoralarea_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electoralarea",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="elections.district"
            ),
        ),
    ]
