# Generated by Django 6.0 on 2026-01-22 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0004_alter_electoralarea_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="elections.district",
            ),
        ),
    ]
