# Generated by Django 6.0 on 2026-01-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0006_alter_user_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="votes",
                to="elections.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="elections.district"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="electoral_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="elections.electoralarea",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="votes",
                to="elections.party",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="elections.province"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="vote_type",
            field=models.CharField(
                choices=[("FPTP", "Candidate Vote"), ("PR", "Party Vote")], max_length=4
            ),
        ),
    ]
