# Generated by Django 6.0 on 2026-01-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0007_alter_vote_candidate_alter_vote_district_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electioncontrol",
            options={
                "verbose_name": "Election Control",
                "verbose_name_plural": "Election Controls",
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="is_nota",
            field=models.BooleanField(default=False),
        ),
    ]
