# Generated by Django 6.0 on 2026-01-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0008_alter_electioncontrol_options_candidate_is_nota"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="voter_id",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
