# Generated by Django 6.0 on 2026-01-28 03:00

import django.db.models.deletion
import elections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0009_user_voter_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", elections.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="elections.district",
            ),
        ),
    ]
